name: getx_stocks_pse
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.6.0
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  get: 4.3.0
  http: ^0.13.3
  intl: ^0.17.0
  mockito: ^5.0.16
  rename: ^2.0.1
  syncfusion_flutter_charts: ^19.2.62

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1
  test: ^1.10.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/app/data/assets/play_store_512.png"

flutter:
  uses-material-design: true
