name: getx_stocks_pse
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  get: 4.3.0
  get_cli: ^1.7.1
  google_fonts: ^2.3.2
  http: ^0.13.3
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.2.62
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_screenutil: ^5.4.0+1
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
